# Exemplo de configuração de secrets do Streamlit para o MEDIX System
# IMPORTANTE: Substitua os valores abaixo por suas credenciais reais

[gcp_service_account]
type = "service_account"
project_id = "medix-system"
private_key_id = "YOUR_PRIVATE_KEY_ID"
# Certifique-se de que as quebras de linha estejam corretas (use \n)
private_key = """-----BEGIN PRIVATE KEY-----
YOUR_PRIVATE_KEY_HERE
-----END PRIVATE KEY-----"""
client_email = "YOUR_SERVICE_ACCOUNT_EMAIL@medix-system.iam.gserviceaccount.com"
client_id = "YOUR_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/YOUR_SERVICE_ACCOUNT_EMAIL%40medix-system.iam.gserviceaccount.com"

# Configuração do sistema
[medix_config]
folder_id = "1HDN1suMspx1um0xbK34waXZ5VGUmseB6"
